package a5;

public enum a {
  APP_IS_LOCKED, COMMAND_MESSAGE_SEND_FAILED, COMMAND_MESSAGE_SENT, CONNECTED, CONNECTING, DEVICES_CHANGED, DEVICE_RESTARTING, LOCALE_CHANGED, OBSERVE_DATABASE, PROGRESSING, SELECTOR_DEVICE_LEFT, SELECTOR_DEVICE_RIGHT, STATE_MESSAGE_RECEIVED, STATE_MESSAGE_RECEIVE_FAILED, STOP_PROGRESSING;
  
  static {
    DEVICES_CHANGED = new a("DEVICES_CHANGED", 1);
    DEVICE_RESTARTING = new a("DEVICE_RESTARTING", 2);
    PROGRESSING = new a("PROGRESSING", 3);
    CONNECTING = new a("CONNECTING", 4);
    CONNECTED = new a("CONNECTED", 5);
    LOCALE_CHANGED = new a("LOCALE_CHANGED", 6);
    STOP_PROGRESSING = new a("STOP_PROGRESSING", 7);
    COMMAND_MESSAGE_SEND_FAILED = new a("COMMAND_MESSAGE_SEND_FAILED", 8);
    COMMAND_MESSAGE_SENT = new a("COMMAND_MESSAGE_SENT", 9);
    STATE_MESSAGE_RECEIVED = new a("STATE_MESSAGE_RECEIVED", 10);
    STATE_MESSAGE_RECEIVE_FAILED = new a("STATE_MESSAGE_RECEIVE_FAILED", 11);
    SELECTOR_DEVICE_RIGHT = new a("SELECTOR_DEVICE_RIGHT", 12);
    SELECTOR_DEVICE_LEFT = new a("SELECTOR_DEVICE_LEFT", 13);
    APP_IS_LOCKED = new a("APP_IS_LOCKED", 14);
    $VALUES = $values();
  }
}


/* Location:              C:\Users\Pooya\Desktop\smartpek\Smart-dex2jar.jar!\a5\a.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */